### ISSUE TITLE
Is Google Drive sync not working?

### ISSUE THREAD

**Issue by bjarte** [VandersonQk/KuroReaderReleases#12]
I have set up Kuro Reader+ Pro on a phone and on an Android tablet and turned on synchronization to Google Drive.

I believe this is supposed to enable me to save the current location in a comic across both devices, but I cannot see any link between them.

It doesn't seem like Kuro is adding anything to my Google Drive either, which would explain why there is no sync.

Is this feature not working because of the ban from Google Play? I have bought the re-uploaded app from Google Play.

Do you know if the sync service will be back at some point?

**Comment by VandersonQk** [comment]
>Do you know if the sync service will be back at some point?

I've just tested the app and checked the API usage, and it's working. So it may be a bug from previous versions with conflicting file permissions, which caused syncing to fail if other versions of Kuro Reader had been previously installed. Please update the app to the latest version on both devices (version 1.6.0, that was released today, 24th) and try again. 

> It doesn't seem like Kuro is adding anything to my Google Drive either

The files are private to the app, so they don't show up in your Google Drive. (You can find and delete the data on the Google Drive website, in "Settings"->"Manage Apps")

> Is this feature not working because of the ban from Google Play?

The ban has no effect on the Google Drive API, the old version is still working. But you can't sync the data between the new and old versions, because they use different API keys.

**Comment by bjarte** [comment]
Thanks for the explanation, I'll update an try again.

/Bjarte

lør. 25. mai 2024, 00:01 skrev Vanderson Oliveira ***@***.***

**Comment by bjarte** [comment]
The sync functionality works great, thank you.
