### ISSUE TITLE
Split double page

### ISSUE THREAD

**Issue by Maybeyok** [VandersonQk/KuroReaderReleases#18]
Can you add the function of splitting double pages?like this Picture []()![IMG_20240804_000108.jpg](https://github.com/user-attachments/assets/ea087483-de21-4cdf-ace8-c3030be75cdb)

**Comment by flesh127** [comment]
Соглы💯

**Comment by bust4cap** [comment]
already covered in #2

**Comment by VandersonQk** [comment]
**Quick update on the development:** I hadn't touched the code for the image viewer for a long time, so it took me a while to remember how it worked, but now it's in the final stages of development (currently in internal testing):

[![Watch the video](https://img.youtube.com/vi/vkTUEmnk1w0/default.jpg)](https://youtu.be/vkTUEmnk1w0)
[Watch the video](https://youtu.be/vkTUEmnk1w0)

*I borrowed this idea from Comic Rack for android, to zoom in on one side instead of splitting the image in two. It's the same effect, but it eliminates the side effects caused by image/bitmap manipulation, mainly reducing cpu and memory usage.

**Comment by VandersonQk** [comment]
Added in [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix)
